#ifndef KRYLOV_H
#define KRYLOV_H

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------
 * Automatically generated by scripts/generate_header.jl -- do not edit.
 * ------------------------------------------------------------------------- */

/* -------------------------------------------------------------------------
 * Enumerators
 * ------------------------------------------------------------------------- */

typedef enum {
  KRYLOV_FLOAT32   = 0,
  KRYLOV_FLOAT64   = 1,
  KRYLOV_COMPLEX32 = 2,
  KRYLOV_COMPLEX64 = 3,
} KrylovDataType;

typedef enum {
  KRYLOV_CPU = 0,
} KrylovDeviceType;

typedef enum {
  KRYLOV_CG = 0,
  KRYLOV_CR = 1,
  KRYLOV_SYMMLQ = 2,
  KRYLOV_MINRES = 3,
  KRYLOV_MINRES_QLP = 4,
  KRYLOV_DIOM = 5,
  KRYLOV_DQGMRES = 6,
  KRYLOV_FOM = 7,
  KRYLOV_GMRES = 8,
  KRYLOV_FGMRES = 9,
  KRYLOV_BICGSTAB = 10,
  KRYLOV_CGS = 11,
  KRYLOV_BILQ = 12,
  KRYLOV_QMR = 13,
  KRYLOV_USYMLQ = 14,
  KRYLOV_USYMQR = 15,
  KRYLOV_TRICG = 16,
  KRYLOV_TRIMR = 17,
  KRYLOV_TRILQR = 18,
  KRYLOV_BILQR = 19,
  KRYLOV_LSLQ = 20,
  KRYLOV_LSQR = 21,
  KRYLOV_LSMR = 22,
  KRYLOV_USYMLQR = 23,
  KRYLOV_CGLS = 24,
  KRYLOV_CRLS = 25,
  KRYLOV_CGNE = 26,
  KRYLOV_CRMR = 27,
  KRYLOV_CRAIG = 28,
  KRYLOV_CRAIGMR = 29,
  KRYLOV_LNLQ = 30,
  KRYLOV_GPMR = 31,
  KRYLOV_CAR = 32,
  KRYLOV_MINARES = 33,
} KrylovSolverType;

/* -------------------------------------------------------------------------
 * Callback types
 *
 * KrylovMatvec: computes y = A*x or y = M\x.
 *   x        : input vector  (read-only, length n)
 *   y        : output vector (write, length m)
 *   userdata : opaque pointer forwarded from krylov_solve
 * ------------------------------------------------------------------------- */

typedef void (*KrylovMatvec)(const void *x, void *y, void *userdata);

/* -------------------------------------------------------------------------
 * API functions
 * ------------------------------------------------------------------------- */

int krylov_workspace_create(KrylovSolverType solver, int m, int n, KrylovDataType dtype, KrylovDeviceType device, void** ws_out);
int krylov_solve(void* ws, KrylovMatvec matvec_A, KrylovMatvec matvec_At, KrylovMatvec matvec_M, const void* b, const void* c, void* userdata, double atol, double rtol, int itmax, int verbose);
int krylov_get_x(void* ws, void* x, int n);
int krylov_get_y(void* ws, void* y, int m);
int krylov_is_solved(void* ws);
int krylov_niter(void* ws);
double krylov_elapsed_time(void* ws);
int krylov_warm_start(void* ws, const void* x0, int n);
int krylov_workspace_free(void* ws);

#ifdef __cplusplus
}
#endif

#endif /* KRYLOV_H */
