#!/usr/bin/env julia
# generate_stores.jl — generates src/c_stores.jl
# Run: julia --startup-file=no --project=<root> scripts/generate_stores.jl
#
# Re-run whenever new solvers are added to Krylov.jl.

# ---------------------------------------------------------------------------
# Solver table: (c_name, workspace_type_name)
# ---------------------------------------------------------------------------
include(joinpath(@__DIR__, "solver_table.jl"))

# ---------------------------------------------------------------------------
# Precision table: (dtype_int, suffix, T_real, FC, S)
# ---------------------------------------------------------------------------
const DTYPES = [
  (0, "f32",  "Float32", "Float32",    "Vector{Float32}"),
  (1, "f64",  "Float64", "Float64",    "Vector{Float64}"),
  (2, "cf32", "Float32", "ComplexF32", "Vector{ComplexF32}"),
  (3, "cf64", "Float64", "ComplexF64", "Vector{ComplexF64}"),
]

# Combo key: solver_idx * 4 + dtype_idx  (max = 33*4+3 = 135, fits UInt8)
combo_key(si, di) = UInt8(si * 4 + di)
store_name(sname, suffix) = "store_$(sname)_$(suffix)"
solver_idx(si) = si - 1   # 0-based, matches KrylovSolverType enum value

# Solvers that require two RHS vectors (b of size m and c of size n)
const TWO_RHS_SOLVERS = Set(["tricg", "trimr", "bilqr", "trilqr", "usymlq", "usymqr", "usymlqr"])

# gpmr uses (A, B, b, c): fptr_At slot is repurposed as the B operator (n×m)
const GPMR_SOLVER = "gpmr"

# ---------------------------------------------------------------------------
# Write c_stores.jl
# ---------------------------------------------------------------------------
out = joinpath(@__DIR__, "..", "src", "c_stores.jl")

open(out, "w") do io
  n_solvers = length(SOLVERS)
  n_combos  = n_solvers * length(DTYPES)

  println(io, """
# c_stores.jl — AUTO-GENERATED by scripts/generate_stores.jl — do not edit.
#
# $(n_solvers) solvers × $(length(DTYPES)) precisions = $(n_combos) typed workspace stores.
# Each store is a Dict{Ptr{Cvoid}, <ConcreteWorkspaceType>} that acts as a
# GC root while keeping types fully concrete for --trim=safe.
#
# Re-generate with:
#   julia --startup-file=no --project=<root> scripts/generate_stores.jl
""")

  # -----------------------------------------------------------------
  # 1. Typed store dicts
  # -----------------------------------------------------------------
  println(io, """
# ---------------------------------------------------------------------------
# Typed workspace stores
# ---------------------------------------------------------------------------
""")
  for (si, (sname, wstype, _)) in enumerate(SOLVERS)
    for (di, (_, suffix, T, FC, S)) in enumerate(DTYPES)
      println(io, "const $(store_name(sname, suffix)) = ",
                  "Dict{Ptr{Cvoid}, Krylov.$(wstype){$(T), $(FC), $(S)}}()")
    end
    println(io)
  end

  # -----------------------------------------------------------------
  # 2. Key index:  handle → UInt8 combo key
  # -----------------------------------------------------------------
  println(io, """
# Single index: handle → combo key (UInt8, max=$(n_combos-1))
const ws_key_store = Dict{Ptr{Cvoid}, UInt8}()
""")

  # -----------------------------------------------------------------
  # 3. Generic typed helpers — compiled once per concrete ws type
  # -----------------------------------------------------------------
  println(io, """
# ---------------------------------------------------------------------------
# Generic typed helpers — specialized per concrete workspace type by the compiler.
# Called from within if-elseif branches where ws has a known concrete type.
# FC is extracted via the where-clause so --trim=safe can infer it statically.
# ---------------------------------------------------------------------------

function _typed_niter(ws)
  Cint(Krylov.iteration_count(ws))
end

function _typed_is_solved(ws)
  Krylov.issolved(ws) ? Cint(1) : Cint(0)
end

function _typed_elapsed_time(ws)
  Cdouble(Krylov.elapsed_time(ws))
end

function _typed_get_x!(ws::Krylov.KrylovWorkspace{T, FC, S}, x_ptr, n) where {T, FC, S}
  x = Krylov.solution(ws, 1)
  copyto!(unsafe_wrap(Vector{FC}, Ptr{FC}(x_ptr), Int(n)), x)
  Cint(0)
end

function _typed_get_y!(ws::Krylov.KrylovWorkspace{T, FC, S}, y_ptr, m) where {T, FC, S}
  Krylov.solution_count(ws) == 2 || return Cint(-2)
  y = Krylov.solution(ws, 2)
  copyto!(unsafe_wrap(Vector{FC}, Ptr{FC}(y_ptr), Int(m)), y)
  Cint(0)
end

function _typed_warm_start!(ws::Krylov.KrylovWorkspace{T, FC, S}, x0_ptr, n) where {T, FC, S}
  # Bypass Krylov.warm_start! to avoid trim-incompatible string interpolation in its
  # error path.  We inline the same logic: allocate Δx if needed, copy x0, set flag.
  hasfield(typeof(ws), :Δx) || return Cint(-2)   # solver does not support warm start
  x0 = unsafe_wrap(Vector{FC}, Ptr{FC}(x0_ptr), Int(n))
  if isempty(ws.Δx)
    ws.Δx = similar(ws.x)
  end
  copyto!(ws.Δx, x0)
  ws.warm_start = true
  Cint(0)
end

# One-RHS solvers — c_ptr is always NULL (ignored)
function _typed_solve!(ws::Krylov.KrylovWorkspace{T, FC, S}, fptr_A, fptr_At, fptr_M, b_ptr, c_ptr, userdata, atol, rtol, itmax, verbose) where {T, FC, S}
  A  = COperator{FC}(ws.m, ws.n, fptr_A, fptr_At, userdata)
  b  = unsafe_wrap(Vector{FC}, Ptr{FC}(b_ptr), ws.m)
  it = itmax > 0 ? Int(itmax) : 0
  kw = (atol=T(atol), rtol=T(rtol), verbose=Int(verbose))
  kw = it > 0 ? merge(kw, (itmax=it,)) : kw
  if fptr_M != C_NULL
    M = CPreconditioner{FC}(ws.n, fptr_M, userdata)
    Krylov.krylov_solve!(ws, A, b; M=M, kw...)
  else
    Krylov.krylov_solve!(ws, A, b; kw...)
  end
  Cint(0)
end

# Two-RHS solvers — c_ptr points to a vector of length n
function _typed_solve_two_rhs!(ws::Krylov.KrylovWorkspace{T, FC, S}, fptr_A, fptr_At, fptr_M, b_ptr, c_ptr, userdata, atol, rtol, itmax, verbose) where {T, FC, S}
  A  = COperator{FC}(ws.m, ws.n, fptr_A, fptr_At, userdata)
  b  = unsafe_wrap(Vector{FC}, Ptr{FC}(b_ptr), ws.m)
  c  = unsafe_wrap(Vector{FC}, Ptr{FC}(c_ptr), ws.n)
  it = itmax > 0 ? Int(itmax) : 0
  kw = (atol=T(atol), rtol=T(rtol), verbose=Int(verbose))
  kw = it > 0 ? merge(kw, (itmax=it,)) : kw
  if fptr_M != C_NULL
    M = CPreconditioner{FC}(ws.n, fptr_M, userdata)
    Krylov.krylov_solve!(ws, A, b, c; M=M, kw...)
  else
    Krylov.krylov_solve!(ws, A, b, c; kw...)
  end
  Cint(0)
end

# GPMR — fptr_At slot is repurposed as B (n×m), distinct from A (m×n)
function _typed_solve_gpmr!(ws::Krylov.KrylovWorkspace{T, FC, S}, fptr_A, fptr_B, fptr_M, b_ptr, c_ptr, userdata, atol, rtol, itmax, verbose) where {T, FC, S}
  A  = COperator{FC}(ws.m, ws.n, fptr_A, C_NULL, userdata)
  B  = COperator{FC}(ws.n, ws.m, fptr_B, C_NULL, userdata)
  b  = unsafe_wrap(Vector{FC}, Ptr{FC}(b_ptr), ws.m)
  c  = unsafe_wrap(Vector{FC}, Ptr{FC}(c_ptr), ws.n)
  it = itmax > 0 ? Int(itmax) : 0
  kw = (atol=T(atol), rtol=T(rtol), verbose=Int(verbose))
  kw = it > 0 ? merge(kw, (itmax=it,)) : kw
  Krylov.krylov_solve!(ws, A, B, b, c; kw...)
  Cint(0)
end
""")

  # -----------------------------------------------------------------
  # 4. Dispatch functions — big if-elseif on the UInt8 combo key
  # -----------------------------------------------------------------
  println(io, """
# ---------------------------------------------------------------------------
# Dispatch functions — generated if-elseif chains over all $(n_combos) combos.
# Each branch has a statically known concrete type: compatible with --trim=safe.
# ---------------------------------------------------------------------------
""")

  # Helper: emit the if-elseif header for a dispatch function
  function emit_dispatch(io, fname, sig, guard, branches_expr, fallback)
    println(io, "function $(fname)($(sig))")
    println(io, "  $(guard) || return $(fallback)")
    println(io, "  k = ws_key_store[ws_ptr]")
    first = true
    for (si, (sname, _, _)) in enumerate(SOLVERS)
      for (di, (_, suffix, _, _, _)) in enumerate(DTYPES)
        key  = combo_key(si-1, di-1)
        sref = "$(store_name(sname, suffix))[ws_ptr]"
        kw   = first ? "if" : "elseif"
        println(io, "  $(kw) k == 0x$(string(key, base=16, pad=2)); $(branches_expr(sref))")
        first = false
      end
    end
    println(io, "  else; $(fallback); end")
    println(io, "end")
    println(io)
  end

  emit_dispatch(io, "_do_niter", "ws_ptr :: Ptr{Cvoid}",
    "haskey(ws_key_store, ws_ptr)",
    sref -> "_typed_niter($(sref))",
    "Cint(-1)")

  emit_dispatch(io, "_do_is_solved", "ws_ptr :: Ptr{Cvoid}",
    "haskey(ws_key_store, ws_ptr)",
    sref -> "_typed_is_solved($(sref))",
    "Cint(-1)")

  emit_dispatch(io, "_do_elapsed_time", "ws_ptr :: Ptr{Cvoid}",
    "haskey(ws_key_store, ws_ptr)",
    sref -> "_typed_elapsed_time($(sref))",
    "Cdouble(-1.0)")

  emit_dispatch(io, "_do_get_x!", "ws_ptr :: Ptr{Cvoid}, x_ptr :: Ptr{Cvoid}, n :: Cint",
    "haskey(ws_key_store, ws_ptr)",
    sref -> "_typed_get_x!($(sref), x_ptr, n)",
    "Cint(-1)")

  emit_dispatch(io, "_do_get_y!", "ws_ptr :: Ptr{Cvoid}, y_ptr :: Ptr{Cvoid}, m :: Cint",
    "haskey(ws_key_store, ws_ptr)",
    sref -> "_typed_get_y!($(sref), y_ptr, m)",
    "Cint(-1)")

  emit_dispatch(io, "_do_warm_start!", "ws_ptr :: Ptr{Cvoid}, x0_ptr :: Ptr{Cvoid}, n :: Cint",
    "haskey(ws_key_store, ws_ptr)",
    sref -> "_typed_warm_start!($(sref), x0_ptr, n)",
    "Cint(-1)")

  # _do_solve! — dispatches to the right helper per solver type
  let sig = join(["ws_ptr :: Ptr{Cvoid}", "fptr_A :: Ptr{Cvoid}", "fptr_At :: Ptr{Cvoid}",
                  "fptr_M :: Ptr{Cvoid}", "b_ptr :: Ptr{Cvoid}", "c_ptr :: Ptr{Cvoid}",
                  "userdata :: Ptr{Cvoid}",
                  "atol :: Cdouble", "rtol :: Cdouble", "itmax :: Cint", "verbose :: Cint"], ", ")
    println(io, "function _do_solve!($(sig))")
    println(io, "  haskey(ws_key_store, ws_ptr) || return Cint(-1)")
    println(io, "  k = ws_key_store[ws_ptr]")
    first = true
    for (si, (sname, _, _)) in enumerate(SOLVERS)
      fn = sname == GPMR_SOLVER ? "_typed_solve_gpmr!" :
           sname in TWO_RHS_SOLVERS ? "_typed_solve_two_rhs!" : "_typed_solve!"
      for (di, (_, suffix, _, _, _)) in enumerate(DTYPES)
        key  = combo_key(si-1, di-1)
        sref = "$(store_name(sname, suffix))[ws_ptr]"
        kw   = first ? "if" : "elseif"
        println(io, "  $(kw) k == 0x$(string(key, base=16, pad=2)); $(fn)($(sref), fptr_A, fptr_At, fptr_M, b_ptr, c_ptr, userdata, atol, rtol, itmax, verbose)")
        first = false
      end
    end
    println(io, "  else; Cint(-1); end")
    println(io, "end")
    println(io)
  end

  # _do_free! — deletes from the right store AND the key index
  println(io, "function _do_free!(ws_ptr :: Ptr{Cvoid})")
  println(io, "  haskey(ws_key_store, ws_ptr) || return Cint(1)")
  println(io, "  k = ws_key_store[ws_ptr]")
  println(io, "  delete!(ws_key_store, ws_ptr)")
  first = true
  for (si, (sname, _, _)) in enumerate(SOLVERS)
    for (di, (_, suffix, _, _, _)) in enumerate(DTYPES)
      key = combo_key(si-1, di-1)
      kw  = first ? "if" : "elseif"
      println(io, "  $(kw) k == 0x$(string(key, base=16, pad=2)); delete!($(store_name(sname, suffix)), ws_ptr)")
      first = false
    end
  end
  println(io, "  end")
  println(io, "  Cint(0)")
  println(io, "end")
  println(io)

  # _do_create! — dispatch on (solver_int, dtype_int), stores in right dict
  println(io, "function _do_create!(solver_int :: Cint, m :: Cint, n :: Cint,")
  println(io, "                     dtype_int :: Cint, ws_out :: Ptr{Ptr{Cvoid}})")
  first = true
  for (si, (sname, wstype, _)) in enumerate(SOLVERS)
    for (di, (dtype_int, suffix, T, FC, S)) in enumerate(DTYPES)
      key      = combo_key(si-1, di-1)
      kw       = first ? "if" : "elseif"
      sref     = store_name(sname, suffix)
      sidx     = solver_idx(si)
      println(io, "  $(kw) solver_int == Cint($(sidx)) && dtype_int == Cint($(dtype_int))")
      println(io, "    ws = Krylov.$(wstype)(Int(m), Int(n), $(S))")
      println(io, "    r  = Base.pointer_from_objref(ws)")
      println(io, "    $(sref)[r] = ws; ws_key_store[r] = 0x$(string(key, base=16, pad=2))")
      println(io, "    unsafe_store!(ws_out, r)")
      first = false
    end
  end
  println(io, "  else")
  println(io, "    return Cint(-2)  # unknown (solver, dtype) combination")
  println(io, "  end")
  println(io, "  Cint(0)")
  println(io, "end")
end

println("Generated $out")
println("  $(length(SOLVERS)) solvers × $(length(DTYPES)) precisions = $(length(SOLVERS)*length(DTYPES)) combos")
