#!/usr/bin/env julia
# Generate interfaces/include/krylov.h from the function_sigs table in LibKrylov.jl
# and the SOLVERS table in generate_stores.jl (single source of truth).
# Usage:  julia interfaces/scripts/generate_header.jl

using Krylov

include(joinpath(@__DIR__, "solver_table.jl"))
include(joinpath(@__DIR__, "..", "src", "LibKrylov.jl"))

# Grab the signature table that LibKrylov.jl populated inside its module
function_sigs = LibKrylov.function_sigs

# ---------------------------------------------------------------------------
# Build KrylovSolverType enum entries from solver_table.jl (single source of truth)
# ---------------------------------------------------------------------------
solver_enum_entries = join(
  ["  $(enum_name) = $(si-1)" for (si, (_, _, enum_name)) in enumerate(SOLVERS)],
  ",\n"
)

block_solver_enum_entries = join(
  ["  $(enum_name) = $(si-1)" for (si, (_, _, enum_name)) in enumerate(BLOCK_SOLVERS)],
  ",\n"
)

# ---------------------------------------------------------------------------
# Write krylov.h
# ---------------------------------------------------------------------------
out_path = joinpath(@__DIR__, "..", "include", "krylov.h")
mkpath(dirname(out_path))

open(out_path, "w") do io
  println(io, """
#ifndef KRYLOV_H
#define KRYLOV_H

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------
 * Automatically generated by scripts/generate_header.jl -- do not edit.
 * ------------------------------------------------------------------------- */

/* -------------------------------------------------------------------------
 * Enumerators
 * ------------------------------------------------------------------------- */

typedef enum {
  KRYLOV_FLOAT32   = 0,
  KRYLOV_FLOAT64   = 1,
  KRYLOV_COMPLEX32 = 2,
  KRYLOV_COMPLEX64 = 3,
} KrylovDataType;

typedef enum {
  KRYLOV_CPU = 0,
} KrylovDeviceType;

typedef enum {
$(solver_enum_entries),
} KrylovSolverType;

typedef enum {
$(block_solver_enum_entries),
} KrylovBlockSolverType;

/* -------------------------------------------------------------------------
 * Callback types
 *
 * KrylovMatvec: computes y = A*x or y = M\\x.
 *   x        : input vector  (read-only, length n)
 *   y        : output vector (write, length m)
 *   userdata : opaque pointer forwarded from krylov_solve
 *
 * KrylovBlockMatvec: block variant for block_gmres / block_minres.
 *   X        : input  block (read-only, n*p, column-major)
 *   Y        : output block (write,      m*p, column-major)
 *   p        : block size (number of columns)
 *   userdata : opaque pointer forwarded from krylov_block_solve
 * ------------------------------------------------------------------------- */

typedef void (*KrylovMatvec)(const void *x, void *y, void *userdata);
typedef void (*KrylovBlockMatvec)(const void *X, void *Y, int p, void *userdata);

/* -------------------------------------------------------------------------
 * API functions
 * ------------------------------------------------------------------------- */
""")

  # Option structs must appear before any function that references them.
  println(io, """
/* -------------------------------------------------------------------------
 * Workspace options (construction-time)
 *
 * Passed to krylov_workspace_create.  These control how the workspace is
 * allocated, so they belong to creation rather than to the solve call.
 * Initialise with krylov_default_workspace_options() before overriding.
 * Sentinel 0 means "use solver default".
 *
 * Fields ignored by a given solver are silently disregarded.
 * ------------------------------------------------------------------------- */

typedef struct {
  int memory;  /* 0 → 20  (GMRES / FGMRES / FOM / DIOM / DQGMRES / GPMR)      */
  int window;  /* 0 → 5   (MINRES / SYMMLQ / LSQR / LSMR / LSLQ)              */
} KrylovWorkspaceOptions;

/* -------------------------------------------------------------------------
 * Solver options (solve-time)
 *
 * Passed to krylov_solve.  Initialise with krylov_default_options() before
 * overriding individual fields.  Sentinel values mean "use solver default":
 *   NaN  for double fields  (atol, rtol, tau, nu)
 *   0    for int fields     (itmax)
 *   0.0  for lambda         (no regularisation, which is the default)
 *
 * Fields ignored by a given solver are silently disregarded.
 * ------------------------------------------------------------------------- */

typedef struct {
  double atol;    /* NaN  → sqrt(eps(T)) per precision                        */
  double rtol;    /* NaN  → sqrt(eps(T)) per precision                        */
  int    itmax;   /* 0    → solver default                                     */
  int    verbose; /* 0    = silent                                             */
  double lambda;  /* 0.0  = no regularisation (LSQR / LSMR / CGLS / ...)     */
  double tau;     /* NaN  → solver default (TriCG / TriMR : 1.0)              */
  double nu;      /* NaN  → solver default (TriCG / TriMR : -1.0)             */
} KrylovOptions;
""")

  for (name, ret, args) in function_sigs
    arg_str = isempty(args) ? "void" : join(["$(ctype) $(aname)" for (aname, ctype) in args], ", ")
    println(io, "$ret $name($arg_str);")
  end

  println(io, """

#ifdef __cplusplus
}
#endif

#endif /* KRYLOV_H */""")
end

println("Generated $out_path")
