#!/usr/bin/env julia
# Generate interfaces/include/krylov.h from the function_sigs table in LibKrylov.jl
# and the SOLVERS table in generate_stores.jl (single source of truth).
# Usage:  julia interfaces/scripts/generate_header.jl

using Krylov

include(joinpath(@__DIR__, "solver_table.jl"))
include(joinpath(@__DIR__, "..", "src", "LibKrylov.jl"))

# Grab the signature table that LibKrylov.jl populated inside its module
function_sigs = LibKrylov.function_sigs

# ---------------------------------------------------------------------------
# Build KrylovSolverType enum entries from solver_table.jl (single source of truth)
# ---------------------------------------------------------------------------
solver_enum_entries = join(
  ["  $(enum_name) = $(si-1)" for (si, (_, _, enum_name)) in enumerate(SOLVERS)],
  ",\n"
)

# ---------------------------------------------------------------------------
# Write krylov.h
# ---------------------------------------------------------------------------
out_path = joinpath(@__DIR__, "..", "include", "krylov.h")
mkpath(dirname(out_path))

open(out_path, "w") do io
  println(io, """
#ifndef KRYLOV_H
#define KRYLOV_H

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------
 * Automatically generated by scripts/generate_header.jl -- do not edit.
 * ------------------------------------------------------------------------- */

/* -------------------------------------------------------------------------
 * Enumerators
 * ------------------------------------------------------------------------- */

typedef enum {
  KRYLOV_FLOAT32   = 0,
  KRYLOV_FLOAT64   = 1,
  KRYLOV_COMPLEX32 = 2,
  KRYLOV_COMPLEX64 = 3,
} KrylovDataType;

typedef enum {
  KRYLOV_CPU = 0,
} KrylovDeviceType;

typedef enum {
$(solver_enum_entries),
} KrylovSolverType;

/* -------------------------------------------------------------------------
 * Callback types
 *
 * KrylovMatvec: computes y = A*x or y = M\\x.
 *   x        : input vector  (read-only, length n)
 *   y        : output vector (write, length m)
 *   userdata : opaque pointer forwarded from krylov_solve
 * ------------------------------------------------------------------------- */

typedef void (*KrylovMatvec)(const void *x, void *y, void *userdata);

/* -------------------------------------------------------------------------
 * API functions
 * ------------------------------------------------------------------------- */
""")

  for (name, ret, args) in function_sigs
    arg_str = join(["$(ctype) $(aname)" for (aname, ctype) in args], ", ")
    println(io, "$ret $name($arg_str);")
  end

  println(io, """

#ifdef __cplusplus
}
#endif

#endif /* KRYLOV_H */""")
end

println("Generated $out_path")
